# a360_curation/.streamlit/secrets.toml

SUPABASE_URL = "https://gjqicqldjgvrwmtkliie.supabase.co"

SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqcWljcWxkamd2cndtdGtsaWllIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzU0MTMyOSwiZXhwIjoyMDczMTE3MzI5fQ.ARd73GaoM_-d9D1R8rWdSacWmwYjNf4FImnurCZMhr8"


